project_name: thedataflows.com/website-server
archives: []
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      # - arm64
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X=main.version={{.Tag}}
    main: main.go
checksum:
  name_template: "sha256sums.txt"
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-SNAPSHOT"
