name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Docker tag
        id: docker_tag
        run: |
          REF=${{ github.ref }}
          if [[ "$REF" == refs/tags/* ]]; then
            echo "::set-output name=tag::${REF#refs/tags/}"
          else
            echo "::set-output name=tag::latest"
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          build-args: VERSION=${{ steps.docker_tag.outputs.tag }}
          push: true
          tags: ghcr.io/${{ github.repository }}/website-server:${{ steps.docker_tag.outputs.tag }}
